name: Release Extension

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  build_and_release:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating a GitHub release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension ZIP
        run: npm run build

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Translate On Hover ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: TranslateOnHover_Production.zip
